version: '3'

services:
  ubuntu:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PROJ_NAME: $PROJ_NAME
        OLD_USER_NAME: $OLD_USER_NAME
        USER_NAME: $USER_NAME
        USER_DIR: $USER_DIR
        GIT_USER_NAME: $GIT_USER_NAME
        GIT_USER_EMAIL: $GIT_USER_EMAIL
        REL_HOME__PROJ: $REL_HOME__PROJ
    volumes:
      - .:${USER_DIR}/${REL_HOME__PROJ}:delegated
    command: bash -c "sleep infinity"
